Description: "Deploy GATK-SV setup on Cromwell EC2 Instance"

Resources:
  DownloadGATKSVRepo:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Content:
        schemaVersion: "0.3"
        description: "Downloads GATK-SV Repo to the EC2 Instance"
        parameters:
          InstanceId:
            description: "ID of the Instance."
            type: "String" 
            default: ""
          AutomationAssumeRole:
            default: ""
            description: "(Optional) The ARN of the role that allows Automation to perform the actions on your behalf."
            type: "String" 
          S3OrFSXPath:
            default: "/FSX_Path_Mounted or s3://BucketHavingData"
            description: "(Required) This is the “S3BucketName” Parameter from the Deployment Part 1 CF Stack. Its same as the FSx mount directory name on servers so just add “/” to the S3BucketName value."
            type: "String" 
        assumeRole: "{{AutomationAssumeRole}}"
        mainSteps:
        - name: "Download"
          action: "aws:runCommand"
          maxAttempts: 3
          timeoutSeconds: 600
          inputs:
            DocumentName: "AWS-RunShellScript"
            InstanceIds:
            - "{{InstanceId}}"
            CloudWatchOutputConfig:
              CloudWatchOutputEnabled: "true"
            Parameters:
              commands: 
                - |
                    #!/bin/bash
                    cd /home/ec2-user
                    git clone https://github.com/goldfinchbio/aws-gatk-sv.git
                    chmod 777 -R aws-gatk-sv
                    sh aws-gatk-sv/scripts/aws_setup_script.sh {{S3OrFSXPath}}
